# Generated by Django 4.2 on 2025-04-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
